<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxu0uae\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxu0uae/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVxu0uae.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVxu0uae\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVxu0uae\appProdProjectContainer([
    'container.build_hash' => 'Vxu0uae',
    'container.build_id' => '19b2febc',
    'container.build_time' => 1670078097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxu0uae');
